---
spring:
  profiles: default

  application:
    name: pinkpony

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/pinkponydev
    username: neo_test
    password:

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    format-sql: true

server:
    port: 8080

logging:
  level.org.springframework.web: INFO
  level.org.hibernate: INFO
#  level.org.apache.coyote.http11: DEBUG # Log all HTTP1.1 stuff

# NOTE: Can use an integrated yml profile - instead of the java -circleci.properties file.
---
spring:
  profiles: circleci

  application:
    name: pinkpony

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ubuntu
    username: ubuntu
    password:

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    format-sql: true
---
spring:
  profiles: cloud

  application:
    name: pinkpony

  datasource:
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    format-sql: true

logging:
  level.org.hibernate: ERROR
  level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  level.org.apache.coyote.http11: DEBUG # Log all HTTP1.1 stuff
